In [1]:
import numpy as np
i=np.array([1,2,3,4,5])
j=i.copy()
i[0]=10
i[1]=20
print(i)
print(j)

[10 20  3  4  5]
[1 2 3 4 5]


In [2]:
import numpy as np 
i=np.array([1,2,3,4,5])
j=i.view()
i[0]=10
j[1]=20
print(i)
print(j)

[10 20  3  4  5]
[10 20  3  4  5]


In [3]:
import numpy as np
i=np.array([1,2,3,4,5])
j=i.view()
j[0]=10
j[1]=20
print(i)
print(j)

[10 20  3  4  5]
[10 20  3  4  5]


In [6]:
import numpy as np
i=np.array([1,2,3,4,5])
j=i.view()
i[0]=10
j[1]=20
print(i)
print(j)
print()
print(i.base)
print(j.base)

[10 20  3  4  5]
[10 20  3  4  5]

None
[10 20  3  4  5]


In [7]:
import numpy as np
i=np.array([1,2,3,4,5])
print(i.shape)

(5,)


In [8]:
import numpy as np
i = np.array([[10, 20, 30, 40, 50],
               [60,70,80,90,100]])
print(i.shape)

(2, 5)


In [9]:
import numpy as np
i = np.array([
    [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]],
    [[10, 20, 30, 40, 50], [60,70,80,90,100],[60,70,80,90,100]]
    ])
print(i.shape)


(2, 3, 5)


In [10]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
j = i.reshape(5,2)
j

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [11]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120])
j = i.reshape(4,3)
j

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [12]:
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,
130, 140,150, 160])
j = i.reshape(2,2,4)
j

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

In [13]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,
130, 140,150, 160])
j = i.reshape(2,4,2)
j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [14]:
import numpy as np
i = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120,
130, 140,150,160])
j = i.reshape(2,4,-1)
j

array([[[ 10,  20],
        [ 30,  40],
        [ 50,  60],
        [ 70,  80]],

       [[ 90, 100],
        [110, 120],
        [130, 140],
        [150, 160]]])

In [17]:
import numpy as np
i = np.array([
 [[10, 20, 30], [40, 50, 60]],
 [[70, 80, 90], [100, 110, 120]],
 [[130, 140,150],[1,2,3]]
 ])
j = i.reshape(-1)


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150,   1,   2,   3])

In [18]:
import numpy as np
i = np.array([[10, 20, 30], [40, 50, 60],[70,80,90]])
j = i.reshape(-1)
j

array([10, 20, 30, 40, 50, 60, 70, 80, 90])